# This workflow ensures that all PRs are correctly labeled

name: LabelChecker
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - run: |
        cd .github/labelChecker
        npm install
        node index.js
